export const CROSS_CHAIN_ORDER_BOOK_ABI = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'InvalidAmounts', type: 'error' },
  { inputs: [], name: 'InvalidExpiry', type: 'error' },
  { inputs: [], name: 'InvalidTimelock', type: 'error' },
  { inputs: [], name: 'NotOrderCreator', type: 'error' },
  { inputs: [], name: 'OrderAlreadyMatched', type: 'error' },
  { inputs: [], name: 'OrderNotActive', type: 'error' },
  { inputs: [], name: 'SameChainNotAllowed', type: 'error' },
  { inputs: [], name: 'UnsupportedChain', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'targetChainId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'sellToken', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'sellAmount', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'buyToken', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'buyAmount', type: 'uint256' },
    ],
    name: 'OrderCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'matcher', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'htlcSwapId', type: 'bytes32' },
    ],
    name: 'OrderMatched',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' }],
    name: 'OrderCompleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' }],
    name: 'OrderCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' }],
    name: 'OrderExpired',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: '_sellToken', type: 'address' },
      { internalType: 'uint256', name: '_sellAmount', type: 'uint256' },
      { internalType: 'address', name: '_buyToken', type: 'address' },
      { internalType: 'uint256', name: '_buyAmount', type: 'uint256' },
      { internalType: 'uint256', name: '_targetChainId', type: 'uint256' },
      { internalType: 'address', name: '_targetAddress', type: 'address' },
      { internalType: 'uint256', name: '_minTimelock', type: 'uint256' },
      { internalType: 'uint256', name: '_expiresAt', type: 'uint256' },
    ],
    name: 'createOrder',
    outputs: [{ internalType: 'uint256', name: 'orderId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_orderId', type: 'uint256' },
      { internalType: 'bytes32', name: '_htlcSwapId', type: 'bytes32' },
    ],
    name: 'matchOrder',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_orderId', type: 'uint256' }],
    name: 'completeOrder',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_orderId', type: 'uint256' }],
    name: 'cancelOrder',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_orderId', type: 'uint256' }],
    name: 'reactivateOrder',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_orderId', type: 'uint256' }],
    name: 'getOrder',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'address', name: 'sellToken', type: 'address' },
          { internalType: 'uint256', name: 'sellAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
          { internalType: 'address', name: 'buyToken', type: 'address' },
          { internalType: 'uint256', name: 'buyAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'targetChainId', type: 'uint256' },
          { internalType: 'address', name: 'targetAddress', type: 'address' },
          { internalType: 'uint256', name: 'minTimelock', type: 'uint256' },
          { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'address', name: 'matchedBy', type: 'address' },
          { internalType: 'bytes32', name: 'htlcSwapId', type: 'bytes32' },
        ],
        internalType: 'struct CrossChainOrderBook.CrossChainOrder',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_targetChainId', type: 'uint256' }],
    name: 'getActiveOrdersForTargetChain',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'address', name: 'sellToken', type: 'address' },
          { internalType: 'uint256', name: 'sellAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
          { internalType: 'address', name: 'buyToken', type: 'address' },
          { internalType: 'uint256', name: 'buyAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'targetChainId', type: 'uint256' },
          { internalType: 'address', name: 'targetAddress', type: 'address' },
          { internalType: 'uint256', name: 'minTimelock', type: 'uint256' },
          { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'address', name: 'matchedBy', type: 'address' },
          { internalType: 'bytes32', name: 'htlcSwapId', type: 'bytes32' },
        ],
        internalType: 'struct CrossChainOrderBook.CrossChainOrder[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_creator', type: 'address' }],
    name: 'getOrdersByCreator',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'address', name: 'sellToken', type: 'address' },
          { internalType: 'uint256', name: 'sellAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
          { internalType: 'address', name: 'buyToken', type: 'address' },
          { internalType: 'uint256', name: 'buyAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'targetChainId', type: 'uint256' },
          { internalType: 'address', name: 'targetAddress', type: 'address' },
          { internalType: 'uint256', name: 'minTimelock', type: 'uint256' },
          { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'address', name: 'matchedBy', type: 'address' },
          { internalType: 'bytes32', name: 'htlcSwapId', type: 'bytes32' },
        ],
        internalType: 'struct CrossChainOrderBook.CrossChainOrder[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSupportedChains',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTotalOrders',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getChainId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'supportedChains',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
