export const HTLC_ABI = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'InvalidAmount', type: 'error' },
  { inputs: [], name: 'InvalidHashlock', type: 'error' },
  { inputs: [], name: 'InvalidParticipant', type: 'error' },
  { inputs: [], name: 'InvalidTimelock', type: 'error' },
  { inputs: [], name: 'SwapAlreadyExists', type: 'error' },
  { inputs: [], name: 'SwapNotActive', type: 'error' },
  { inputs: [], name: 'TimelockExpired', type: 'error' },
  { inputs: [], name: 'TimelockNotExpired', type: 'error' },
  { inputs: [], name: 'TransferFailed', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'swapId', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'initiator', type: 'address' },
      { indexed: true, internalType: 'address', name: 'participant', type: 'address' },
      { indexed: false, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'bytes32', name: 'hashlock', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'timelock', type: 'uint256' },
    ],
    name: 'SwapCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'swapId', type: 'bytes32' },
      { indexed: false, internalType: 'bytes32', name: 'secret', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'participant', type: 'address' },
    ],
    name: 'SwapWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'swapId', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'initiator', type: 'address' },
    ],
    name: 'SwapRefunded',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: '_swapId', type: 'bytes32' },
      { internalType: 'address', name: '_participant', type: 'address' },
      { internalType: 'bytes32', name: '_hashlock', type: 'bytes32' },
      { internalType: 'uint256', name: '_timelock', type: 'uint256' },
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'createSwap',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: '_swapId', type: 'bytes32' },
      { internalType: 'bytes32', name: '_secret', type: 'bytes32' },
    ],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '_swapId', type: 'bytes32' }],
    name: 'refund',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '_swapId', type: 'bytes32' }],
    name: 'getSwap',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'initiator', type: 'address' },
          { internalType: 'address', name: 'participant', type: 'address' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'bytes32', name: 'hashlock', type: 'bytes32' },
          { internalType: 'uint256', name: 'timelock', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
        ],
        internalType: 'struct HTLC.Swap',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '_swapId', type: 'bytes32' }],
    name: 'isSwapActive',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '_secret', type: 'bytes32' }],
    name: 'getHashlock',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getSwapsAsInitiator',
    outputs: [{ internalType: 'bytes32[]', name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getSwapsAsParticipant',
    outputs: [{ internalType: 'bytes32[]', name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_initiator', type: 'address' },
      { internalType: 'address', name: '_participant', type: 'address' },
      { internalType: 'bytes32', name: '_hashlock', type: 'bytes32' },
      { internalType: 'uint256', name: '_timelock', type: 'uint256' },
    ],
    name: 'generateSwapId',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
